name = "teleworker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "teleworker-db"
database_id = "df74560f-a911-44f0-9aa0-b6f873b48e49"
migrations_dir = "drizzle/migrations"
